os:
    - linux
    - osx

sudo: required

env:
    global:
        # Your package name
        - PACKAGE="UnitTesting-example"
    matrix:
        # - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/dev/sbin/travis.sh

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_syntax_tests

notifications:
    email: false
